repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        exclude: |
          (?x)^(
            docs/source/conf\.py
            | data/scrape\.py
          )$