# The name of the action
name: Unit Tests using Pytest
# When the action is triggered
on:
  push:
    branches:
      - master
      - main
      - '*/*'
      - '*'
  pull_request:
    branches:
      - master
      - main
      - '*/*'
      - '*'

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  build:
    # Run on a MACOS VM
    runs-on: macos-latest
    steps:
      # Checkout the GitHub repo
      - uses: actions/checkout@v2

      # Install Python 3.12.6
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.6"

      # Pip install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Move into the project tests folder (./tests) and run pytest
      - name: Framework Unit Tests with pytest
        working-directory: ./tests
        run: pytest